foreground            #e1e2e8
background            #111418
selection_foreground  #111418
selection_background  #a3c9fe
cursor                #a3c9fe
cursor_text_color     #111418
url_color             #d8bde3

color0                #111418
color8                #43474e
color1                #ffb4ab
color9                #ffb4ab
color2                #d8bde3
color10               #d8bde3
color3                #bbc7db
color11               #3c4858
color4                #a3c9fe
color12               #1d4875
color5                #d3e4ff
color13               #d3e4ff
color6                #3c2947
color14               #533f5e
color7                #e1e2e8
color15               #e1e2e8
