foreground            #f1dfda
background            #1a110f
selection_foreground  #1a110f
selection_background  #ffb4a2
cursor                #ffb4a2
cursor_text_color     #1a110f
url_color             #dac58c

color0                #1a110f
color8                #534340
color1                #93000a
color9                #ffdad6
color2                #dac58c
color10               #dac58c
color3                #e7bdb3
color11               #5d4038
color4                #ffb4a2
color12               #723425
color5                #ffdad2
color13               #ffdad2
color6                #3c2f04
color14               #544519
color7                #f1dfda
color15               #f1dfda
