set -g @matugen_bg "#131318"
set -g @matugen_fg "#e4e1e9"
set -g @matugen_primary "#c2c1ff"
set -g @matugen_secondary "#c6c4dd"
set -g @matugen_tertiary "#e9b9d2"
set -g @matugen_surface "#131318"
set -g @matugen_surface_variant "#47464f"
set -g @matugen_error "#ffb4ab"
