# Set the CPU energy performance bias to 'power' mode on battery
CPU_ENERGY_PERF_POLICY_ON_BAT="power"

# Set aggressive power management for SATA devices on battery
SATA_LINKPWR_ON_BAT="med_power_with_dipm"
