preload = ~/.config/backgrounds/aesthetic_deer.jpg
preload = ~/.config/backgrounds/city_top_view.jpg
preload = ~/.config/backgrounds/city-rain.png
preload = ~/.config/backgrounds/deer_and_sunset.jpg
preload = ~/.config/backgrounds/deer_in_pine_forest.jpg
preload = ~/.config/backgrounds/dunes-sun.jpg
preload = ~/.config/backgrounds/highlands-grid.jpg

ipc = true

wallpaper = , ~/.config/backgrounds/aesthetic_deer.jpg
