format = """
$python\
$directory\
$git_branch\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$conda\
"""

command_timeout = 5000

[username]
show_always = true
style_user = ""
style_root = ""
format = '[ ]($style)'

[directory]
style = ""
format = '[ $path ❯ ]($style)'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = ""
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = ""
format = '[ $symbol $branch ]($style)'
ignore_branches = ["main", "master"]

[golang]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = ""
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = ""
format = '[ $symbol ($version) ]($style)'

[python]
style = ""
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = ""
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = ""
format = '[ $time ]($style)'

[conda]
format = '[(\($environment\))  ]($style)'
style = ""
ignore_base = false
