# Specify the devices to target.
# The below line targets all event devices. 
# For more precision, you might specify only your keyboard by its hardware ID.
# device /dev/input/event*

# [ids] section identifies device matching patterns.
[ids]
*

# [main] section defines the remapping rules.
# This example maps Caps Lock such that when tapped it sends Escape,
# and when held down it functions as Control.
[main]
capslock = overload(control, esc)

# Home-row mod mappings (example):
# when you tap a key, it sends its normal keypress;
# when you hold it, ita = overloadt(control, a, 200)
a = overloadt(control, a, 400)
s = overloadt(shift, s, 400)
d = overloadt(meta, d, 400)
f = overloadt(alt, f, 400)

# j = overloadt(alt, j, 200)
# k = overloadt(meta, k, 200)
# l = overloadt(shift, l, 200)
# ; = overloadt(control, ;, 200)

