[ids]
*

[main]
capslock = overload(control, esc)
layer = hrm

[hrm]
a = overload(control, a)
s = overload(alt, s)
d = overload(shift, d)
f = overload(super, f)
j = overload(super, j)
k = overload(shift, k)
l = overload(alt, l)
ö = overload(control, ö)
