$primary        = rgb({{colors.primary.default.hex_stripped}})
$secondary      = rgb({{colors.secondary.default.hex_stripped}})
$background     = rgb({{colors.background.default.hex_stripped}})
$surface        = rgb({{colors.surface.default.hex_stripped}})
$error          = rgb({{colors.error.default.hex_stripped}})
$on_background  = rgb({{colors.on_background.default.hex_stripped}})
$tertiary       = rgb({{colors.tertiary.default.hex_stripped}})

$primary_hex        = {{colors.primary.default.hex_stripped}}
$secondary_hex      = {{colors.secondary.default.hex_stripped}}
$background_hex     = {{colors.background.default.hex_stripped}}
$surface_hex        = {{colors.surface.default.hex_stripped}}
$error_hex          = {{colors.error.default.hex_stripped}}
$on_background_hex  = {{colors.on_background.default.hex_stripped}}
$tertiary_hex       = {{colors.tertiary.default.hex_stripped}}
