set -g @matugen_bg "{{colors.background.default.hex}}"
set -g @matugen_fg "{{colors.on_background.default.hex}}"
set -g @matugen_primary "{{colors.primary.default.hex}}"
set -g @matugen_secondary "{{colors.secondary.default.hex}}"
set -g @matugen_tertiary "{{colors.tertiary.default.hex}}"
set -g @matugen_surface "{{colors.surface.default.hex}}"
set -g @matugen_surface_variant "{{colors.surface_variant.default.hex}}"
set -g @matugen_error "{{colors.error.default.hex}}"
